### ISSUE TITLE
消息过长导致的服务端错误

### ISSUE THREAD

**Issue by WangEdward** [gaowanliang/DownloadBot#27]
## 运行环境 ##
Debian 10, 使用 DownloadBot_0.0.5_Linux_x86_64.tar.gz 安装

## 报错内容 ##
```
2021/05/24 18:29:50 [{86e3eeffd4b075f6}] Download started!
2021/05/24 18:29:51 [{86e3eeffd4b075f6}] Download paused!
2021/05/24 18:29:51 Bad Request: message is too long
panic: Bad Request: message is too long

goroutine 14 [running]:
log.Panic(0xc00029b730, 0x1, 0x1)
        D:/program_app/go/src/log/log.go:351 +0xac
main.dropErr(...)
        D:/program_data/go/DownloadBot/main.go:14
main.TMSelectMessage(0xc000155c20)
        D:/program_data/go/DownloadBot/Telegram.go:169 +0x1a0d
created by main.tgBot
        D:/program_data/go/DownloadBot/Telegram.go:707 +0x85d
```

## 可能原因 ##
根据TG官方文档， API 每条消息只能支持4096字节，或许可使用分段方式发送？

**Comment by gaowanliang** [comment]
目前准备做成图片的形式，但是怎么展示还没想好
