### ISSUE TITLE
上传重复的问题

### ISSUE THREAD

**Issue by WangEdward** [gaowanliang/DownloadBot#28]
## 情况描述 ##
![对于 G Drive, 多次上传将产生多个文件夹](https://i.loli.net/2021/05/24/TGlMAFuHYeDkmps.png " 对于 G Drive, 多次上传将产生多个文件夹")
对于 G Drive, 多次上传将产生多个文件夹

---
![](https://i.loli.net/2021/05/24/EPRakOgQTJALm3V.png)
对于 onedrive，多次上传将产生带后缀的文件（虽然在同文件夹中），

---
并且onedrive无法上传大文件

**tg 聊天记录**
> ...There was a connection problem when uploading downloads/100MB.bin. Retrying. It's the 9 times retrying
>
>DownloadFolder upload to OneDrive complete

在输出上述内容后，程序报错退出
```
2021/05/24 19:06:20 Failed to Restore :The Content-Range header length does not match the provided number of bytes.
panic: Failed to Restore :The Content-Range header length does not match the provided number of bytes.

goroutine 70 [running]:
log.Panicf(0xaef62c, 0x15, 0xc0001e3f40, 0x1, 0x1)
        D:/program_app/go/src/log/log.go:358 +0xc0
onedrive.restore.func1(0xc000548670, 0xc00019bc20, 0xb114b8, 0xb114c0, 0xc0004c3620, 0x29, 0xc0000b2288, 0xc00051be00, 0x13, 0xc0000b22b8, ...)
        D:/program_data/go/DownloadBot/vendor/onedrive/onedrive.go:104 +0x299
created by onedrive.restore
        D:/program_data/go/DownloadBot/vendor/onedrive/onedrive.go:94 +0x207
```

**Comment by gaowanliang** [comment]
GD问题已记录，下面这个应该是你的文件有问题
