### ISSUE TITLE
运行./DownloadBot时报错

### ISSUE THREAD

**Issue by SakuraH-LY** [gaowanliang/DownloadBot#37]
2021/07/23 01:51:31 strconv.ParseInt: parsing "": invalid syntax
panic: strconv.ParseInt: parsing "": invalid syntax

goroutine 37 [running]:
log.Panic(0xc00025f3a8, 0x1, 0x1)
        D:/program_app/go/src/log/log.go:351 +0xac
main.dropErr(...)
        D:/program_data/go/DownloadBot/main.go:14
main.toInt64(0x0, 0x0, 0x4)
        D:/program_data/go/DownloadBot/utils.go:514 +0x9d
main.TMSelectMessage(0xc000212c80)
        D:/program_data/go/DownloadBot/Telegram.go:62 +0x4e
created by main.tgBot
        D:/program_data/go/DownloadBot/Telegram.go:707 +0x85d

**Comment by YoghurtGuy** [comment]
同样的报错
```
"output": {
    "telegram": {
      "bot-key": "777777777:Aaaaaaaaaa",
      "user-id": "555555555555"
    }
  }
```
这样不对吗?
