### ISSUE TITLE
运行./DownloadBot时报错 json: cannot unmarshal number into Go value of type main.Config

### ISSUE THREAD

**Issue by GJKen** [gaowanliang/DownloadBot#47]
2021/11/30 21:15:51 json: cannot unmarshal number into Go value of type main.Config
panic: json: cannot unmarshal number into Go value of type main.Config

goroutine 1 [running]:
log.Panic(0xc00035fe08, 0x1, 0x1)
        /usr/local/go/src/log/log.go:354 +0xae
main.dropErr(...)
        /tmp/Down/DownloadBot/main.go:14
main.init.0()
        /tmp/Down/DownloadBot/main.go:24 +0x173

**Comment by gaowanliang** [comment]
请贴上你的config.json文件内容，重要数据请自行脱敏

**Comment by GJKen** [comment]
{
    "aria2-server": "ws://127.0.0.1:6800/jsonrpc",
    "aria2-key": "gjken",
    "bot-key": "2123699668:AAE5YcKQiVGlWc2-PVsazCt0_0BtLPyu_uk",
    "user-id": "1111153343",
    "max-index": 10,
    "sign":"GJK_DL_bot",
    "language":"zh-CN",
    "downloadFolder":"/tmp/Down",
    "moveFolder":"/tmp/GoogleDrive"
}

**Comment by GJKen** [comment]
我更新了报错信息

**Comment by gaowanliang** [comment]
connect: connection refused 表示Aria没开，或者是你ws地址有问题，又或者你aria没开ws
