### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by lloyd18** [gaowanliang/DownloadBot#63]
其实我的用途非常简单，只想用TG看下载进度而已，报错了~

能修复一下吗，系统 Ubuntu20.04，出错代码：

2022/08/31 01:33:17 Too Many Requests: retry after 42
panic: Too Many Requests: retry after 42

goroutine 589 [running]:
log.Panic(0xc00020d9f8, 0x1, 0x1)
        D:/program_app/go/src/log/log.go:351 +0xac
main.dropErr(...)
        D:/program_data/go/DownloadBot/main.go:14
main.activeRefresh.func1(0x0, 0x26b9095f, 0xc00056a140, 0xc0004dc6e0, 0x2d0)
        D:/program_data/go/DownloadBot/Telegram.go:553 +0x234
main.activeRefresh(0xa3, 0xc00056a140, 0xc0004dc6e0, 0xb5ab)
        D:/program_data/go/DownloadBot/Telegram.go:596 +0x159
created by main.tgBot

**Comment by Swor-dart** [comment]
自己编译啊，你没看出来这编译是在win下执行的吗？？？？？

**Comment by Swor-dart** [comment]
自己编译啊，你没看出来这编译是在win下执行的吗？？？？？
