### ISSUE TITLE
最新源码编译的运行报错

### ISSUE THREAD

**Issue by cachexy123** [gaowanliang/DownloadBot#68]
2022/12/21 16:27:21 配置資訊載入完成！
2022/12/21 16:27:21 與 ws://127.0.0.1:6800/jsonrpc 連接中
2022/12/21 16:27:21 Aria2 websocket連接已建立！Aria2版本：1.36.0
2022/12/21 16:27:21 已登入授權帳戶 xx_bot
panic: message "tgCommandSetMaxLengthDes" not found in language "zh-TW"

goroutine 25 [running]:
github.com/nicksnyder/go-i18n/v2/i18n.(*Localizer).MustLocalize(0x5efea6, 0x0)
	/root/ceshi/DownloadBot/vendor/github.com/nicksnyder/go-i18n/v2/i18n/localizer.go:211 +0x3a
main.locText({0xc0002434d8, 0x1, 0x10000c00002d380})
	/root/ceshi/DownloadBot/utils.go:156 +0xc7
main.setCommands(0xc000463bf0)
	/root/ceshi/DownloadBot/Telegram.go:40 +0xc9
main.tgBot({0xc00002a3f0, 0x2e}, 0xc0003cc520)
	/root/ceshi/DownloadBot/Telegram.go:842 +0xb9c
created by main.main
	/root/ceshi/DownloadBot/main.go:34 +0xc8

**Comment by Swor-dart** [comment]
是不是只留了个编译好的文件，clone后一些文件夹还是必要的，你没仔细看源码吧。
