### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by RemKeeper** [gaowanliang/DownloadBot#69]
![image](https://user-images.githubusercontent.com/78486275/220437924-f55a10ef-91bb-4f4b-818e-15a98f332eca.png)

使用Start或者转发文件就会崩溃

2023-02-22 03:14:09     INFO    服务器监听在 [::]:23369
2023-02-22 03:14:11     INFO    与 http://10.32.0.151:6800/jsonrpc 连接中
2023-02-22 03:14:11     INFO    Aria2 websocket连接已建立！Aria2版本：1.36.0
2023-02-22 03:14:11     INFO    已登入授权账户 xx
2023-02-22 03:14:36     PANIC   %!w(*tgbotapi.Error=&{400 Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 10 {0 0}})
panic: %!w(*tgbotapi.Error=&{400 Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 10 {0 0}})

goroutine 14 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x0?, {0x0?, 0x0?, 0xc00038e2a0?})
        D:/DownloadBot/vendor/go.uber.org/zap/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000096340, {0x0, 0x0, 0x0})
        D:/DownloadBot/vendor/go.uber.org/zap/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*SugaredLogger).log(0xc00049fa90, 0x4, {0x8066e9?, 0x14e6e8?}, {0xc0004a06c0?, 0x80?, 0x78?}, {0x0, 0x0, 0x0})    
        D:/DownloadBot/vendor/go.uber.org/zap/sugar.go:295 +0xee
go.uber.org/zap.(*SugaredLogger).Panicf(...)
        D:/DownloadBot/vendor/go.uber.org/zap/sugar.go:189
DownloadBot/tool/zap.Panic({0x8066e9?, 0x0?}, {0xc0004a06c0?, 0x0?, 0x0?})
        D:/DownloadBot/tool/zap/zap.go:119 +0xb5
DownloadBot/tool/output/telegram.dropErr(...)
        D:/DownloadBot/tool/output/telegram/telegram.go:36
DownloadBot/tool/output/telegram.Aria2Bot({0xc00002ef30, 0x2e}, 0xc0000ac270)
        D:/DownloadBot/tool/output/telegram/telegram.go:488 +0x1d9d
created by main.main
        D:/DownloadBot/cmd/DownloadBot/main.go:43 +0xd8

RPC地址可以正常使用
![image](https://user-images.githubusercontent.com/78486275/220438322-d29cc2c6-9964-480e-acaf-dc208bf2c2c5.png)

**Comment by RemKeeper** [comment]
![image](https://user-images.githubusercontent.com/78486275/220568359-fbb1ce64-0f53-4696-9ae9-fcc7c8430134.png)
好像是不能够获取过大文件的链接……

**Comment by gaowanliang** [comment]
不支持tg文件的下载
